apiVersion: v1
kind: Service
metadata:
  name: matrixcx-website-tenthmatrix
spec:
  selector:
    app: matrixcx-website-tenthmatrix
  ports:
    - port: 3005
      targetPort: 3005
  type: LoadBalancer
